name: base
channels:
  - conda-forge
  - bioconda
  - default
dependencies:
  - python=3.12
  - setuptools
  - pip
  - wheel
  - conda[version='>=23.7']
  - conda-build
  - conda-content-trust
  - conda-libmamba-solver
  - conda-pack
  - conda-package-handling
  - conda-package-streaming
  - conda-token
